<?php
declare(strict_types = 1);

namespace App\SocketIO;

use Swoole\Http\Request;

class SocketIO extends \Hyperf\SocketIOServer\SocketIO
{
    public function onOpen($server, Request $request) : void
    {
        //TODO OnOpen
        parent::onOpen($server, $request); // TODO: Change the autogenerated stub
    }

    public function onClose($server, int $fd, int $reactorId) : void
    {
        //TODO onClose
        parent::onClose($server, $fd, $reactorId); // TODO: Change the autogenerated stub
    }
}
